### ISSUE TITLE
Failed to calculate Centroid when creating new property

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#1597]
When creating property with large area, there is exception when calculating centroid (using point on surface). Below is the exception:
```
GEOS_ERROR: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 25.777153773692557 -28.163815361161124 at 25.777153773692557 -28.163815361161124

django.contrib.gis ERROR libgeos.py L99: GEOS_ERROR: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 25.777153773692557 -28.163815361161124 at 25.777153773692557 -28.163815361161124

Internal Server Error: /api/property/create/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/web/project/django_project/frontend/api_views/property.py", line 206, in post
    'centroid': geom.point_on_surface
  File "/usr/local/lib/python3.10/site-packages/django/contrib/gis/geos/geometry.py", line 585, in point_on_surface
    return self._topology(capi.geos_pointonsurface(self.ptr))
  File "/usr/local/lib/python3.10/site-packages/django/contrib/gis/geos/libgeos.py", line 153, in __call__
    return self.func(*args)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/gis/geos/prototypes/threadsafe.py", line 47, in __call__
    return self.cfunc(self.thread_context.handle.ptr, *args)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/gis/geos/prototypes/errcheck.py", line 32, in check_geom
    raise GEOSException(
django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSPointOnSurface_r".
```

When I check using ST_IsValid function, the geometry is indeed invalid. The geometry is below:
![image](https://github.com/kartoza/sawps/assets/5819076/fd6178e4-baf1-4741-b425-52be5e9f7e88)

@timlinux @LunaAsefaw any idea, Is this happened because the geometry is from union of several parcels?

**Comment by LunaAsefaw** [comment]
@danangmassandy similar issues on QGIS and postgresql
![image](https://github.com/kartoza/sawps/assets/90245715/29f8ae58-5a24-41de-b45e-67d6b0789e6f)
![image](https://github.com/kartoza/sawps/assets/90245715/f4d8be3f-47f1-431a-8096-7e3d123ce76b)

Then I ran fix geometries first then generate centroid and it worked
![image](https://github.com/kartoza/sawps/assets/90245715/719797c6-c88d-4fc9-8e31-0bf42f7e55a0)

Similar functions for this could be ST_MakeValid() before the centroid is generated. 
![image](https://github.com/kartoza/sawps/assets/90245715/7e8b9746-3633-4028-afa0-ad96aa6c2728)

**Comment by danangmassandy** [comment]
I am not quite sure why, but now the issue does not exist anymore. I cannot reproduce the exception even though the geometry is invalid in postgis. cc: @LunaAsefaw
![image](https://github.com/kartoza/sawps/assets/5819076/a34d52de-872c-4f99-a113-20428d8525a1)

My upload was successful and the centroid is correctly calculated.
![image](https://github.com/kartoza/sawps/assets/5819076/627e6a20-9d83-4ac0-87fe-f22f19538c9d)


Source:
[invalid_property_geom.json](https://github.com/kartoza/sawps/files/13633309/invalid_property_geom.json)
